services:
  llm_api:
    image: ghcr.io/magn4/llm_api:latest
    ports:
      - "9191:9191"
    container_name: llm_api
    # restart: unless-stopped

  extract_pdf:
    image: ghcr.io/magn4/extract_pdf:latest
    ports:
      - "5001:5001"
    container_name: extract_pdf
    restart: unless-stopped

  main_controller:
    image: ghcr.io/magn4/main_controller:latest
    ports:
      - "5002:5002"
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      restart: unless-stopped

  auth:
    image: ghcr.io/magn4/auth:latest
    ports:
      - "5003:5003"
    container_name: auth
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    # restart: unless-stopped

  db:
    image: ghcr.io/magn4/database:latest
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  anki_service:
    image: ghcr.io/magn4/anki_service:latest
    ports:
      - "8000:8000"
    container_name: anki_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  nginx:
    image: ghcr.io/magn4/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - extract_pdf
      - main_controller
      - anki_service
    restart: unless-stopped

volumes:
  db_data:
